### ISSUE TITLE
Collision detection sometimes does not work

### ISSUE THREAD

**Issue by icedvariables** [Hawkie/SpaceCommand#2]
When working on the landing state I noticed that sometimes the ship crashes despite being quite high above the group. I have no idea how the collision detection works so I haven't been able to try and fix it! [Example.](http://i.imgur.com/qf2wCZf.png)

**Comment by Hawkie** [comment]
The hit test works on the basis of a closed polygon. If the landscape was below the start and end point, the ship would hittest against an imaginary line between the start and end point above the landing area and landscape. 
Temp fix by adding a start and end point below the screen
